---

- name: Add Elasticsearch apt key.
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add logstash-forwarder repository.
  apt_repository: repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main' state=present

- name: Check if logstash-forwarder is already installed.
  stat: path=/etc/init.d/logstash-forwarder
  register: logstash_forwarder_installed

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_forwarder_installed.stat.exists == false

- name: Install logstash-forwarder.
  apt: pkg=logstash-forwarder state=present

# See: http://goo.gl/cz9Lnd
- name: Install logstash-forwarder init script.
  copy: src=logstash-forwarder.deb.init dest=/etc/init.d/logstash-forwarder mode=0755

- name: Create logstash-forwarder configuration file.
  template: src=logstash-forwarder.j2 dest=/etc/logstash-forwarder mode=0644
  notify: restart logstash-forwarder

- name: Ensure Logstash SSL key pair directory exists.
  file: path="{{ logstash_forwarder.ssl_dir }}" state=directory

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ logstash_forwarder.ssl_certificate_file }}"
    dest: "{{ logstash_forwarder.ssl_dir }}/{{ logstash_forwarder.ssl_certificate_file | basename }}"
    mode: 0644
  notify: restart logstash-forwarder

- name: Ensure logstash-forwarder is started and enabled on boot.
  service: name=logstash-forwarder state=started enabled=yes
